sudo: required

services:
  - docker

before_install:
  - docker build -t obanlatomiwa/docker-react-project -f Dockerfile.dev .

script:
  - docker run obanlatomiwa/docker-react-project npm run test -- --coverage