language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t obanlatomiwa/docker-react-project -f Dockerfile.dev .

script:
  - docker run -e CI=true obanlatomiwa/docker-react-project npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-project"
  env: "Dockerreactproject-env"
  bucket_name: "elasticbeanstalk-us-east-2-517315340481"
  bucket_path: "docker-react-project"

  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"