version: '3'
services:
  react-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]